[package]
name = "store"
version = "0.1.17"
edition = "2024"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.10.2"
chrono = "0.4.40"
sqlx = {version = "0.8.3", features = ["postgres", "runtime-tokio-rustls", "runtime-tokio", "macros", "migrate"]} 
tera = "1.20.0"
